default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: lfberge_blog_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: lfberge_blog_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: lfberge_blog_production
  pool: 5
  timeout: 5000
